services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: petstore
      POSTGRES_USER: petstore
      POSTGRES_PASSWORD: petstore
    ports:
      - "5432:5432"
    volumes:
      - petstore-db:/var/lib/postgresql/data

volumes:
  petstore-db:
